In [ ]:
import numpy as np
arr1 = np.empty((2,2))
print(arr1)

[2 2]


In [ ]:
import numpy as np
One_Array = np.ones((4,2))
print(One_Array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
filled = np.full((2,4),3)
print(filled)

[[3 3 3 3]
 [3 3 3 3]]


In [ ]:
import numpy as np
Zeros = np.zeros_like((2,3))
print(Zeros)


[0 0]


In [ ]:
import numpy as np
Ones = np.ones_like((2,3))
print(Ones)

[1 1]


In [ ]:
import numpy as np
new_List= [1,2,3,4,5]
arr = np.array(new_List)
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
values = np.arange(10 , 49)
print(values)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
import numpy as np
matrix = np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np
Matrix = np.eye(3,3)
print(Matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
Random_Num = np.random.randomt(30)
Random_Mean=(np.mean(Random_Num))
print(Random_Mean)

23.0


In [ ]:
import numpy as np
Random_value = np.random.random((10,10))
print(Random_value.min())
print(Random_value.max())

0.000271406489110948
0.9959505062980393


In [ ]:
import numpy as np
Zero_array = np.zeros(10)
Zero_array[4] = 1
print(Zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
arr = [1,2,0,0,4,0]
arr = arr[::-1]
print(arr)

[0, 4, 0, 0, 2, 1]


In [ ]:
import numpy as np
arr = np.ones((3,3))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print("Add = ",np.add(arr1,arr2))
print("Subtract = ",np.subtract(arr1,arr2))
print("dot = ",np.dot(arr1,arr2))
print("Square = ",np.sqrt(arr1))
print("Product = ",np.multiply(arr1,arr2))

Add =  [[2 4]
 [6 8]]
Subtract =  [[0 0]
 [0 0]]
dot =  [[ 7 10]
 [15 22]]
Square =  [[1.         1.41421356]
 [1.73205081 2.        ]]
Product =  [[ 1  4]
 [ 9 16]]
